### ISSUE TITLE
Error building node-gyp on windows 10

### ISSUE THREAD

**Issue by euclidesdry** [TeamDock/photon#2]
When I'm running the development mode, I see the following errors:

``` node
                    errorOut=gyp info it worked if it ends with ok
    gyp info using node-gyp@5.1.0
    gyp info using node@14.18.1 | win32 | x64
    gyp info find Python using Python version 3.9.5 found at "C:\Python39\python.exe"
    gyp http GET https://electronjs.org/headers/v16.0.5/node-v16.0.5-headers.tar.gz
    gyp http 200 https://electronjs.org/headers/v16.0.5/node-v16.0.5-headers.tar.gz
    gyp http GET https://electronjs.org/headers/v16.0.5/SHASUMS256.txt
    gyp http GET https://electronjs.org/headers/v16.0.5/win-x86/node.lib
    gyp http GET https://electronjs.org/headers/v16.0.5/win-x64/node.lib
    gyp http GET https://electronjs.org/headers/v16.0.5/win-arm64/node.lib
    gyp http 200 https://electronjs.org/headers/v16.0.5/win-x64/node.lib
    gyp http 200 https://electronjs.org/headers/v16.0.5/win-x86/node.lib
    gyp http 200 https://electronjs.org/headers/v16.0.5/SHASUMS256.txt
    gyp http 200 https://electronjs.org/headers/v16.0.5/win-arm64/node.lib
    gyp ERR! find VS
    gyp ERR! find VS msvs_version not set from command line or npm config
    gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
    gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
    gyp ERR! find VS looking for Visual Studio 2015
    gyp ERR! find VS - not found
    gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
    gyp ERR! find VS
    gyp ERR! find VS **************************************************************
    gyp ERR! find VS You need to install the latest version of Visual Studio
    gyp ERR! find VS including the "Desktop development with C++" workload.
    gyp ERR! find VS For more information consult the documentation at:
    gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
    gyp ERR! find VS **************************************************************
    gyp ERR! find VS
    gyp ERR! configure error
    gyp ERR! stack Error: Could not find any Visual Studio installation to use
    gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
    gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
    gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
    gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
    gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
    gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7      
    gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16     
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
    gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
    gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
    gyp ERR! System Windows_NT 10.0.19044
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd D:\.Dev\GitHub\photon\node_modules\node-pty
    gyp ERR! node -v v14.18.1
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
error Command failed with exit code 1.
```

**Comment by pedrinfx** [comment]
What is your node version?

**Comment by pedrinfx** [comment]
You can install the "Desktop development with C++" without the Visual Studio to run, or you use "npm install --global windows-build-tools" in you terminal

**Comment by euclidesdry** [comment]
> You can install the "Desktop development with C++" without the Visual Studio to run, or you use "npm install --global windows-build-tools" in your terminal

If the normal user (I mean non-programmer) tries downloading and executing the Photon app, do will he/she get the same issues that I have?

**Comment by pedrinfx** [comment]
> > You can install the "Desktop development with C++" without the Visual Studio to run, or you use "npm install --global windows-build-tools" in your terminal
> 
> If the normal user (I mean non-programmer) tries downloading and executing the Photon app, do will he/she get the same issues that I have?

No, because it is built, this problem only can occur in development environment.

**Comment by euclidesdry** [comment]
Ok, but, I tried to download the app (.exe) and install it, the software came with the same bug/issue.

**Comment by pedrinfx** [comment]
This is really strange, can you take a print?

**Comment by euclidesdry** [comment]
Yes, and I did!
![image](https://user-images.githubusercontent.com/57298973/147478624-d049c023-aaf7-4278-817a-72da91a3efad.png)

**Comment by pedrinfx** [comment]
> Yes, and I did! ![image](https://user-images.githubusercontent.com/57298973/147478624-d049c023-aaf7-4278-817a-72da91a3efad.png)

The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.

**Comment by pedrinfx** [comment]
> Yes, and I did! ![image](https://user-images.githubusercontent.com/57298973/147478624-d049c023-aaf7-4278-817a-72da91a3efad.png)

The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.

**Comment by pedrinfx** [comment]
> Yes, and I did! ![image](https://user-images.githubusercontent.com/57298973/147478624-d049c023-aaf7-4278-817a-72da91a3efad.png)

The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.

**Comment by pedrinfx** [comment]
> > Yes, and I did! (Image)
> 
> The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.

**Comment by euclidesdry** [comment]
> > Yes, and I did! (Image)
> 
> The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.

Yeah, I see, you can use Windows Sandbox to execute a windows machine like VirtualBox, which is an isolated environment that lets you run temporary windows inside your OS if you're using Windows 10 of course.

Here is the reference: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview

**Comment by pedrinfx** [comment]
> > > Yes, and I did! (Image)
> 
> > 
> 
> > The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.
> 
> 
> 
> Yeah, I see, you can use Windows Sandbox to execute a windows machine like VirtualBox, which is an isolated environment that lets you run temporary windows inside your OS if you're using Windows 10 of course.
> 
> 
> 
> Here is the reference: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview

Oh, I was look for a virtual machine, thanks for the tip.

**Comment by euclidesdry** [comment]
> > > > Yes, and I did! (Image)
> > 
> > 
> > > 
> > 
> > 
> > > The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.
> > 
> > 
> > Yeah, I see, you can use Windows Sandbox to execute a windows machine like VirtualBox, which is an isolated environment that lets you run temporary windows inside your OS if you're using Windows 10 of course.
> > Here is the reference: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview
> 
> Oh, I was look for a virtual machine, thanks for the tip.

Cool,
 I finally got to set upping my PC to start the software development.
 
 That was hard but I got it!!!
 
![Captura - Windows Software Developer](https://user-images.githubusercontent.com/57298973/147845967-cd06bc89-9f0f-4813-8efe-4fb60c3d4888.png)

 
![image](https://user-images.githubusercontent.com/57298973/147845956-8c7f7c9e-80ec-4ea3-ba92-d553429ce8f7.png)


That only worked when I installed Visual Studio.

**Comment by pedrinfx** [comment]
> > > > > Yes, and I did! (Image)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.
> 
> > > 
> 
> > > 
> 
> > > Yeah, I see, you can use Windows Sandbox to execute a windows machine like VirtualBox, which is an isolated environment that lets you run temporary windows inside your OS if you're using Windows 10 of course.
> 
> > > Here is the reference: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview
> 
> > 
> 
> > Oh, I was look for a virtual machine, thanks for the tip.
> 
> 
> 
> Cool,
> 
>  I finally got to set upping my PC to start the software development.
> 
>  
> 
>  That was hard but I got it!!
> 
> 
> 
> 
> 
> That only worked when I installed Visual Studio.

Nice, as you can see the font is not correct, but in the next patch i'll fix that. You can fix that installing Source Code Pro, but you can wait for the next patch.

**Comment by euclidesdry** [comment]
> > > > > > Yes, and I did! (Image)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Yeah, I see, you can use Windows Sandbox to execute a windows machine like VirtualBox, which is an isolated environment that lets you run temporary windows inside your OS if you're using Windows 10 of course.
> > 
> > 
> > > > Here is the reference: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview
> > 
> > 
> > > 
> > 
> > 
> > > Oh, I was look for a virtual machine, thanks for the tip.
> > 
> > 
> > Cool,
> > I finally got to set upping my PC to start the software development.
> > That was hard but I got it!!
> > That only worked when I installed Visual Studio.
> 
> Nice, as you can see the font is not correct, but in the next patch i'll fix that. You can fix that installing Source Code Pro, but you can wait for the next patch.

OK, but, you put in the project the Docker dependency too, no?

**Comment by pedrinfx** [comment]
> > > > > > > Yes, and I did! (Image)
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > Yeah, I see, you can use Windows Sandbox to execute a windows machine like VirtualBox, which is an isolated environment that lets you run temporary windows inside your OS if you're using Windows 10 of course.
> > > 
> > > 
> > > > > Here is the reference: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Oh, I was look for a virtual machine, thanks for the tip.
> > > 
> > > 
> > > Cool,
> > > I finally got to set upping my PC to start the software development.
> > > That was hard but I got it!!
> > > That only worked when I installed Visual Studio.
> > 
> > 
> > Nice, as you can see the font is not correct, but in the next patch i'll fix that. You can fix that installing Source Code Pro, but you can wait for the next patch.
> 
> OK, but, you put in the project the Docker dependency too, no?

The Docker is recommended to use to build the binaries, but you can use `npm run release`, but it not recommend on Windows

**Comment by euclidesdry** [comment]
> > > > > > > > Yes, and I did! (Image)
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > > The issue didn't occur because of node-gyp, but a bug that I forgot to fix, I'll release the patch soon.
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > Yeah, I see, you can use Windows Sandbox to execute a windows machine like VirtualBox, which is an isolated environment that lets you run temporary windows inside your OS if you're using Windows 10 of course.
> > > > 
> > > > 
> > > > > > Here is the reference: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Oh, I was look for a virtual machine, thanks for the tip.
> > > > 
> > > > 
> > > > Cool,
> > > > I finally got to set upping my PC to start the software development.
> > > > That was hard but I got it!!
> > > > That only worked when I installed Visual Studio.
> > > 
> > > 
> > > Nice, as you can see the font is not correct, but in the next patch i'll fix that. You can fix that installing Source Code Pro, but you can wait for the next patch.
> > 
> > 
> > OK, but, you put in the project the Docker dependency too, no?
> 
> The Docker is recommended to use to build the binaries, but you can use `npm run release`, but it not recommend on Windows

Right!

I'll take some days to learn how to implement Docker in the Coding projects, and I'll return to develop new features for Proton.
