### ISSUE TITLE
Updating package maker to Electron Forge istead of electron builder

### ISSUE THREAD

**Issue by euclidesdry** [TeamDock/photon#3]
The idea is to change the Electron package maker to ` Electron Forge`  instead of `electron builder` because `electron builder` needs to install additional resources like MS Visual Studio to run correctly, however, `Electron Forge` doesn't want any additional software or package to be installed on Developer PC.

**Comment by pedrinfx** [comment]
If you can, make a pull request with your idea, but, you can solve the problem using: "npm install --global windows-build-tools".

**Comment by euclidesdry** [comment]
> If you can, make a pull request with your idea, but, you can solve the problem using: "npm install --global windows-build-tools".

I'm trying to Install windows-build-tools package, but I got a terrible loop waiting for the instalation.

**Comment by pedrinfx** [comment]
> > If you can, make a pull request with your idea, but, you can solve the problem using: "npm install --global windows-build-tools".
> 
> I'm trying to Install windows-build-tools package, but I got a terrible loop waiting for the instalation.

Another alternative would be to install "Desktop development with C++"

**Comment by euclidesdry** [comment]
I think that I need to do it because I get stuck in a freezy screen while I'm installing windows-build-tools, which got +4 hour on this screen: 
![image](https://user-images.githubusercontent.com/57298973/147399542-5f6ce650-2358-4828-8b5b-403a53438dcf.png)

I will try to download the "Desktop development with C++", my doubts came why the package is huge.

**Comment by pedrinfx** [comment]
Install the "Desktop development with C++" is unnecessarily hard, I'll try o implement the Electron Forge on Photon app.

**Comment by euclidesdry** [comment]
> Install the "Desktop development with C++" is unnecessarily hard, I'll try o implement the Electron Forge on Photon app.

![Net 4 8 Log Error](https://user-images.githubusercontent.com/57298973/147478785-3eb7cbcc-adb6-46b6-a67b-3abc786e6ca0.png)

I think that my PC is against me right now 😅😅😂. I tried to do that a bunch of times!

**Comment by pedrinfx** [comment]
I think install the Visual Studio with "Desktop development with C++" can solve the problem, but, in this case, you must to install the Visual Studio.

**Comment by euclidesdry** [comment]
> I think install the Visual Studio with "Desktop development with C++" can solve the problem, but, in this case, you must to install the Visual Studio.

I don't have enough disk space available to do this, unfortunately, 😢😢...
